name: fjr25_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - httpx
    - python-dotenv
    - pydantic
    - supabase
    - PyJWT
    - cryptography
